kind: ConfigMap
metadata:
  name: nginx-proxy-config
  namespace: default
data:
  default: |
    server {
        listen       9080;
        server_name  _;

        location / {
            proxy_pass  $host;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
            proxy_set_header REMOTE-HOST        $remote_addr;
            proxy_set_header X-Forwarded-Proto  $scheme;
            proxy_redirect off;
        }
    }